### ISSUE TITLE
system error

### ISSUE THREAD

**Issue by MarcelBulpr** [realcr/mailman_docker#4]
hello,

I gone through your tutorial to get the mail-server to work and I'm glad to find one like that but it is not working properly. I created my own server.conf file, ran "sudo ./build_images.sh" without a problem but "sudo ./initial_data_cont.sh" gives me following error message:

"Code: System error

Message: not a directory
## Frames:

0: setupRootfs
Package: github.com/docker/libcontainer
## File: rootfs_linux.go@29

1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
## File: standard_init_linux.go@52

2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
## File: factory_linux.go@223

3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
## File: init.go@35

4: Init
Package: github.com/docker/docker/pkg/reexec
## File: reexec.go@26

5: main
Package: main
## File: docker.go@29

6: main
Package: runtime
## File: proc.c@220

7: goexit
Package: runtime
File: proc.c@1394
FATA[0000] Error response from daemon: Cannot start container 746f1310bffc54fff7843b3c010df781ac0c21e2aa16076550bb75a6c13a912e: [8] System error: not a directory "

neither me nor my co-workers could find the problem, would be nice if you could do a little trouble shoot :smile: .

I use Ubuntu 14.04.

Thanks in advance.

**Comment by realcr** [comment]
Hi Marcel, Thank you for sending this.
I have never seen that error message before, and it seems like something is strange with your docker installation. Note that all the trace you have included is related to the Go language, while this repository doesn't have even one line of Go code. 

I am trying to start the docker containers myself right now. I fail to pass the apt-get update stage (It gives me some errors). I will update you when I manage to get it running :)

**Comment by realcr** [comment]
I made some changes to the Dockerfile (Using ubuntu:wiley instead of 14.04). It works for me.
Please check if it works for you now.

If the same error happens, I suggest that you check your docker installation.

**Comment by MarcelBulpr** [comment]
thank you man,

it works without any problems now.

**Comment by realcr** [comment]
My pleasure :)
